import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { Category } from "@/types/types";
import { seedAuth } from "../auth/auth";
import { AssetDoc } from "../types/asset-types";
import { LiabilityDoc } from "../types/liability-types";
import { Asset, Liability, Statement } from "./models";
import dbConnect from "./mongodb";

type YearData = {
  year: number;
  lastYearSalary: number;
  assets: AssetDoc[];
  liabilities: LiabilityDoc[];
};

const testUserData = {
  name: "Bob Stone",
  email: "dev@gmail.com",
  password: "password",
};

function getData(userId: string): YearData[] {
  return [
    {
      year: 2010,
      lastYearSalary: 52000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 3200,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 5800,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 3000,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          contribution: { self: 2600 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 1500,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          contribution: { nonSelf: 2600 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 2000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 1500,
          category: Category.AfterTax,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 28000 },
        { userId, title: "Car Loan", amount: 12500 },
        { userId, title: "Credit Card", amount: 2400 },
      ],
    },
    {
      year: 2011,
      lastYearSalary: 54000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 3800,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 7200,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 5600,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 3000,
          contribution: { self: 2700 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 2800,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 1500,
          contribution: { nonSelf: 2700 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 4200,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 2000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 2200,
          category: Category.AfterTax,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 24500 },
        { userId, title: "Car Loan", amount: 9800 },
        { userId, title: "Credit Card", amount: 1800 },
      ],
    },
    {
      year: 2012,
      lastYearSalary: 56500,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 4100,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 9500,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 9200,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 5600,
          contribution: { self: 2825 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 4600,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 2800,
          contribution: { nonSelf: 2825 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 7000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 4200,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 4500,
          category: Category.AfterTax,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 20800 },
        { userId, title: "Car Loan", amount: 6900 },
        { userId, title: "Credit Card", amount: 950 },
      ],
    },
    {
      year: 2013,
      lastYearSalary: 59000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 5200,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 12000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 14333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 9200,
          contribution: { self: 2950 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 7167,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 4600,
          contribution: { nonSelf: 2950 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 10800,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 7000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 8200,
          category: Category.AfterTax,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 16900 },
        { userId, title: "Car Loan", amount: 3800 },
        { userId, title: "Credit Card", amount: 1200 },
      ],
    },
    {
      year: 2014,
      lastYearSalary: 63000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 6500,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 15000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 20800,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 14333,
          contribution: { self: 3150 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 10400,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 7167,
          contribution: { nonSelf: 3150 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 15500,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 10800,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 12000,
          category: Category.AfterTax,
        },
        {
          userId,
          title: "Primary Residence",
          amount: 220000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 12500 },
        { userId, title: "Mortgage", amount: 192000 },
        { userId, title: "Credit Card", amount: 2100 },
      ],
    },
    {
      year: 2015,
      lastYearSalary: 67000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 7200,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 18000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 28000,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 20800,
          contribution: { self: 3350 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 14000,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 10400,
          contribution: { nonSelf: 3350 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 20800,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 15500,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 16500,
          category: Category.AfterTax,
        },
        {
          userId,
          title: "Primary Residence",
          amount: 228000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 8000 },
        { userId, title: "Mortgage", amount: 187500 },
        { userId, title: "Credit Card", amount: 1500 },
      ],
    },
    {
      year: 2016,
      lastYearSalary: 72000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 8100,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 22000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 36667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 28000,
          contribution: { self: 3600 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 18333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 14000,
          contribution: { nonSelf: 3600 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 27500,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 20800,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 22000,
          category: Category.AfterTax,
        },
        {
          userId,
          title: "Primary Residence",
          amount: 238000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Student Loan", amount: 3200 },
        { userId, title: "Mortgage", amount: 182800 },
        { userId, title: "Credit Card", amount: 800 },
      ],
    },
    {
      year: 2017,
      lastYearSalary: 78000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 9500,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 26000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 47333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 36667,
          contribution: { self: 3900 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 23667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 18333,
          contribution: { nonSelf: 3900 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 35500,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 27500,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 31000,
          category: Category.AfterTax,
        },
        {
          userId,
          title: "Primary Residence",
          amount: 252000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 165000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 177800 },
        { userId, title: "Rental Property Mortgage", amount: 138000 },
        { userId, title: "Credit Card", amount: 1400 },
      ],
    },
    {
      year: 2018,
      lastYearSalary: 84000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 11000,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 30000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 54667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 47333,
          contribution: { self: 4200 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 27333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 23667,
          contribution: { nonSelf: 4200 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 40000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 35500,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 36000,
          category: Category.AfterTax,
        },
        {
          userId,
          title: "Primary Residence",
          amount: 265000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 172000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 172500 },
        { userId, title: "Rental Property Mortgage", amount: 133000 },
        { userId, title: "Credit Card", amount: 2200 },
      ],
    },
    {
      year: 2019,
      lastYearSalary: 90000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 13500,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 35000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 68667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 54667,
          contribution: { self: 4500 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 34333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 27333,
          contribution: { nonSelf: 4500 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 51000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 40000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 48000,
          category: Category.AfterTax,
        },
        { userId, title: "HSA", amount: 8500, category: Category.TaxFree },
        {
          userId,
          title: "Primary Residence",
          amount: 280000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 180000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 166800 },
        { userId, title: "Rental Property Mortgage", amount: 127800 },
        { userId, title: "Credit Card", amount: 1800 },
      ],
    },
    {
      year: 2020,
      lastYearSalary: 95000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 18000,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 52000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 78667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 68667,
          contribution: { self: 4750 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 39333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 34333,
          contribution: { nonSelf: 4750 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 62000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 51000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 67000,
          category: Category.AfterTax,
        },
        { userId, title: "HSA", amount: 12000, category: Category.TaxFree },
        {
          userId,
          title: "Primary Residence",
          amount: 310000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 192000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 160800 },
        { userId, title: "Rental Property Mortgage", amount: 122400 },
        { userId, title: "Credit Card", amount: 900 },
      ],
    },
    {
      year: 2021,
      lastYearSalary: 105000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 22000,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 60000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 105333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 78667,
          contribution: { self: 5250 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 52667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 39333,
          contribution: { nonSelf: 5250 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 84000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 62000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 98000,
          category: Category.AfterTax,
        },
        { userId, title: "HSA", amount: 16500, category: Category.TaxFree },
        {
          userId,
          title: "Primary Residence",
          amount: 370000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 230000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 154500 },
        { userId, title: "Rental Property Mortgage", amount: 116700 },
        { userId, title: "Credit Card", amount: 3200 },
      ],
    },
    {
      year: 2022,
      lastYearSalary: 115000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 19000,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 55000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 98667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 105333,
          contribution: { self: 5750 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 49333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 52667,
          contribution: { nonSelf: 5750 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 74000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 84000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 82000,
          category: Category.AfterTax,
        },
        { userId, title: "HSA", amount: 19000, category: Category.TaxFree },
        {
          userId,
          title: "Primary Residence",
          amount: 390000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 245000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 148000 },
        { userId, title: "Rental Property Mortgage", amount: 110800 },
        { userId, title: "Credit Card", amount: 4500 },
        { userId, title: "HELOC", amount: 22000 },
      ],
    },
    {
      year: 2023,
      lastYearSalary: 122000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 21000,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 62000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 118667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 98667,
          contribution: { self: 6100 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 59333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 49333,
          contribution: { nonSelf: 6100 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 92000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 74000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 105000,
          category: Category.AfterTax,
        },
        { userId, title: "HSA", amount: 23500, category: Category.TaxFree },
        {
          userId,
          title: "Primary Residence",
          amount: 405000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 258000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 141200 },
        { userId, title: "Rental Property Mortgage", amount: 104700 },
        { userId, title: "Credit Card", amount: 2800 },
        { userId, title: "HELOC", amount: 15000 },
      ],
    },
    {
      year: 2024,
      lastYearSalary: 130000,
      assets: [
        {
          userId,
          title: "Checking Account",
          amount: 25000,
          category: Category.Cash,
        },
        {
          userId,
          title: "Savings Account",
          amount: 72000,
          category: Category.Cash,
        },
        {
          userId,
          title: "401(k)",
          amount: 143333,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 118667,
          contribution: { self: 6500 },
        },
        {
          userId,
          title: "401(k) Company Match",
          amount: 71667,
          category: Category.TaxDeferred,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 59333,
          contribution: { nonSelf: 6500 },
        },
        {
          userId,
          title: "Roth IRA",
          amount: 115000,
          category: Category.TaxFree,
          retirement: true,
          includeInGrowthCalculation: true,
          amountOneYearAgo: 92000,
          contribution: { self: 2000 },
        },
        {
          userId,
          title: "Brokerage Account",
          amount: 138000,
          category: Category.AfterTax,
        },
        { userId, title: "HSA", amount: 28000, category: Category.TaxFree },
        {
          userId,
          title: "Primary Residence",
          amount: 425000,
          category: Category.Property,
        },
        {
          userId,
          title: "Rental Property",
          amount: 272000,
          category: Category.Property,
        },
      ],
      liabilities: [
        { userId, title: "Mortgage", amount: 134100 },
        { userId, title: "Rental Property Mortgage", amount: 98400 },
        { userId, title: "Credit Card", amount: 1900 },
        { userId, title: "HELOC", amount: 8000 },
      ],
    },
  ];
}

async function seed() {
  await dbConnect();

  await Asset.deleteMany();
  await Liability.deleteMany();
  await Statement.deleteMany();

  const userId = (await seedAuth.api.signUpEmail({ body: testUserData })).user
    .id;
  const data = getData(userId);

  for (const {
    year,
    lastYearSalary,
    assets: assetsInput,
    liabilities: liabilitiesInput,
  } of data) {
    const assets = await Asset.insertMany(assetsInput);
    const liabilities = await Liability.insertMany(liabilitiesInput);
    await Statement.create({
      userId,
      year,
      lastYearSalary,
      assets: assets.map((a) => a._id),
      liabilities: liabilities.map((l) => l._id),
    });
  }

  console.log("seeded db with 15 years of data (2010–2024)");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
